language: node_js
node_js:
  - 10
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
  - npm install -g @angular/cli
install:
  - cd rss-temple/
  - npm ci
script:
  - npm run test-ci
  - npm run e2e-ci
after_script:
  - node_modules/codecov/bin/codecov --disable=gcov
