language: node_js
node_js:
    - "8"
cache:
    directories:
        - rss-temple/node_modules
before_script:
    - npm install -g @angular/cli
script:
    - cd rss-temple/
    - npm install
    - npm run build

